-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSWei9ffRT7tLriWJG8COoV64YB9gPX8q9pAm8mWktV+gCgYIKoZIzj0DAQehRANCAASfK65CALx/CDp3/gAnCzRAJbSWKesQLE4MbhBZjvSHkfFZ45Tigs7KcGEWLyynno7IUHvoHAdORdM3shPrzq81
-----END PRIVATE KEY-----